
version: '3.8'

services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password@12345
      POSTGRES_DB: new_employee_db
    ports:
      - "5501:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - custom_network

  backend:
    build: ./Backend
    restart: always
    environment:
      PORT: 3501
      HOST: 0.0.0.0
      DB_USER: postgres
      DB_PASSWORD: Password@12345
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: new_employee_db
    ports:
      - "3501:3501"
    depends_on:
      - database
    networks:
      - custom_network

  frontend:
    build: ./Frontend
    restart: always
    ports:
      - "8502:80"
    networks:
      - custom_network

  hr_page:
    build: ./HR_Page
    restart: always
    ports:
      - "8503:80"
    networks:
      - custom_network

volumes:
  db_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16

